# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish github npm package 

on: 
  push:
    branches:
      - master
    paths:
      - tsconfig-project/**
  workflow_dispatch:

permissions:
  contents: write  

jobs: 
  npm-publish:
    runs-on: ubuntu-latest 

    defaults:
      run:
        working-directory: tsconfig-project

    steps: 
      - uses: actions/checkout@v2

      # Setup Node.js 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: git config user.email "sohaibkhiaf@gmail.com"
      - run: git config user.name "@github-ci"

      - run: yarn version --patch --message "Bump version to %s"

      - run: git push 

      - run: git push --follow-tags

      - name: publish to github 
        run: | 
          npm config set registry '//npm.pkg.github.com' 
          npm set '//npm.pkg.github.com/:_authToken' "${{ env.NODE_AUTH_TOKEN }}"
          npm run publish:github
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      


