# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Pull request example

on: 
  workflow_dispatch:

jobs: 
  
  pull-request:
    runs-on: ubuntu-latest 

    defaults:
      run:
        working-directory: typescript-project

    steps: 
      - uses: actions/checkout@v2

      # Setup Node.js 
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      # Install yarn
      - name: Install yarn
        run: npm install --global yarn

      # Install libraries
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run tests
      - name: Run tests
        run: yarn test

