# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Pull request example

on: 
  workflow_dispatch:

jobs: 
  pull-request:
    runs-on: ubuntu-latest 

    defaults:
      run:
        working-directory: typescript-project

    steps: 
      - uses: actions/checkout@v2

      # Setup Node.js 
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      # Install yarn
      - name: Install yarn
        run: npm install --global yarn

      # Install libraries
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run linting
      - name: Run linting 
        run: yarn lint

      # Compile the code 
      - name: Build project
        run: yarn build

      # Run tests
      - name: Run tests
        run: yarn test

