# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Sectet example

on: 
  workflow_dispatch:

jobs: 
  test-secret:
    runs-on: ubuntu-latest 

    steps: 
      - name: Test secret
        run: |
          echo "Masked secret"
          echo ${{ secrets.TEST_SECRET }}
          echo "Secret:"
          echo ${{ secrets.TEST_SECRET }} | sed 's/./&/g'



